# Change these first
owner: mwmbl # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Mwmbl Front End
    url: https://mwmbl.org
  - name: Mwmbl API
    url: https://api.mwmbl.org/api/v1/search/?s=test
  - name: Mwmbl Book
    url: https://book.mwmbl.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mwmbl.org 
 # baseUrl: /your-repo-name
  logoUrl: https://mwmbl.org/logo.svg
  name: Mwmbl Status
  introTitle: "[Mwmbl](https://mwmbl.org) is the free and open-source search engine powered by community"
  introMessage: "Please join our [community](https://matrix.to/#/#mwmbl:matrix.org) for news and updates"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
